# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kpl.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("kpl.proto", :syntax => :proto2) do
    add_message "AggregatedRecord" do
      repeated :partition_key_table, :string, 1
      repeated :explicit_hash_key_table, :string, 2
      repeated :records, :message, 3, "Record"
    end
    add_message "Tag" do
      required :key, :string, 1
      optional :value, :string, 2
    end
    add_message "Record" do
      required :partition_key_index, :uint64, 1
      optional :explicit_hash_key_index, :uint64, 2
      required :data, :bytes, 3
      repeated :tags, :message, 4, "Tag"
    end
  end
end

AggregatedRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AggregatedRecord").msgclass
Tag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tag").msgclass
Record = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Record").msgclass
